"""Default tenant unit catalog based on UN/CEFACT Recommendation 20 codes."""

DEFAULT_UNITS = (
    ("H87", "Pieza", "Piece", "pz", "count", 0),
    ("C62", "Unidad", "Unit", "u", "count", 0),
    ("DZN", "Docena", "Dozen", "doc", "count", 0),
    ("PR", "Par", "Pair", "par", "count", 0),
    ("SET", "Juego", "Set", "jgo", "count", 0),
    ("XBX", "Caja", "Box", "caja", "package", 0),
    ("XPK", "Paquete", "Package", "paq", "package", 0),
    ("XBG", "Bolsa", "Bag", "bolsa", "package", 0),
    ("XRL", "Rollo", "Reel", "rollo", "package", 0),
    ("XPL", "Tarima", "Pallet", "tarima", "package", 0),
    ("KGM", "Kilogramo", "Kilogram", "kg", "mass", 3),
    ("GRM", "Gramo", "Gram", "g", "mass", 3),
    ("MGM", "Miligramo", "Milligram", "mg", "mass", 3),
    ("TNE", "Tonelada métrica", "Metric tonne", "t", "mass", 3),
    ("LBR", "Libra", "Pound", "lb", "mass", 3),
    ("ONZ", "Onza", "Ounce", "oz", "mass", 3),
    ("MTR", "Metro", "Metre", "m", "length", 3),
    ("CMT", "Centímetro", "Centimetre", "cm", "length", 3),
    ("MMT", "Milímetro", "Millimetre", "mm", "length", 3),
    ("KMT", "Kilómetro", "Kilometre", "km", "length", 3),
    ("INH", "Pulgada", "Inch", "in", "length", 3),
    ("FOT", "Pie", "Foot", "ft", "length", 3),
    ("YRD", "Yarda", "Yard", "yd", "length", 3),
    ("MTK", "Metro cuadrado", "Square metre", "m²", "area", 3),
    ("CMK", "Centímetro cuadrado", "Square centimetre", "cm²", "area", 3),
    ("MMK", "Milímetro cuadrado", "Square millimetre", "mm²", "area", 3),
    ("HAR", "Hectárea", "Hectare", "ha", "area", 3),
    ("LTR", "Litro", "Litre", "L", "volume", 3),
    ("MLT", "Mililitro", "Millilitre", "mL", "volume", 3),
    ("MTQ", "Metro cúbico", "Cubic metre", "m³", "volume", 3),
    ("CMQ", "Centímetro cúbico", "Cubic centimetre", "cm³", "volume", 3),
    ("GLL", "Galón estadounidense", "US gallon", "gal", "volume", 3),
    ("SEC", "Segundo", "Second", "s", "time", 3),
    ("MIN", "Minuto", "Minute", "min", "time", 3),
    ("HUR", "Hora", "Hour", "h", "time", 3),
    ("DAY", "Día", "Day", "d", "time", 3),
    ("WEE", "Semana", "Week", "sem", "time", 3),
    ("MON", "Mes", "Month", "mes", "time", 3),
    ("ANN", "Año", "Year", "a", "time", 3),
    ("KWH", "Kilowatt hora", "Kilowatt hour", "kWh", "energy", 3),
    ("WHR", "Watt hora", "Watt hour", "Wh", "energy", 3),
    ("KWT", "Kilowatt", "Kilowatt", "kW", "power", 3),
    ("WTT", "Watt", "Watt", "W", "power", 3),
    ("AMP", "Ampere", "Ampere", "A", "electric", 3),
    ("VLT", "Volt", "Volt", "V", "electric", 3),
    ("CEL", "Grado Celsius", "Degree Celsius", "°C", "temperature", 2),
    ("KEL", "Kelvin", "Kelvin", "K", "temperature", 2),
    ("PAL", "Pascal", "Pascal", "Pa", "pressure", 3),
    ("BAR", "Bar", "Bar", "bar", "pressure", 3),
    ("P1", "Porcentaje", "Percent", "%", "ratio", 3),
)
