export function createInitialState({ authConfigured = false } = {}) {
  return {
    active: "produccion",
    activeSubmodule: null,
    history: [],
    theme: localStorage.getItem("erclave-theme") || "light",
    lang: localStorage.getItem("erclave-lang") || "es",
    adminApi: { status: "idle", data: null, error: "" },
    sessionApi: { status: "idle", data: null, error: "" },
    productionApi: { status: "idle", error: "" },
    inventoryApi: { status: "idle", error: "" },
    permissionEditor: null,
    inventoryMovements: { status: "idle", error: "" },
    finishedGoodsReceipts: { status: "idle", orders: [], summaries: [], products: [], error: "" },
    operationalHandoffs: {},
    warehouseProductionRequests: {status:"idle",data:[],page:{offset:0,has_more:false},error:""},
    warehouseMaterialRequests: { status: "idle", data: [], page: {offset:0,has_more:false}, error: "" },
    inventoryItems: { status: "idle", error: "" },
    inventoryBalances: { status: "idle", data: [], page: {}, error: "", queryKey: "", cursor: "", previousCursors: [] },
    hrApi: { status: "idle", error: "", workers: [] },
    salesApi: { status: "idle", error: "", referenceWarnings: [], workers: [], references: { currencies: [], payment_terms: [] } },
    salesServiceOrderDetail: { status: "idle", id: "", data: null, error: "" },
    purchasingApi: { status: "idle", error: "", suppliers: [], requisitions: [], orders: [], receipts: [], items: [], warehouses: [] },
    purchasingSupplierEditId: "",
    purchasingRequisitionEditId: "",
    purchasingOrderEditId: "",
    purchasingOrderSourceRequisitionId: "",
    purchasingReceiptSourceOrderId: "",
    maintenanceApi: { status: "idle", error: "", orders: [], workers: [], machines: [], productionOrders: [], items: [], warehouses: [] },
    maintenanceSourceOrderId: "",
    maintenanceMaterialSourceOrderId: "",
    unitCatalog: { status: "idle", data: [], error: "" },
    tenantResolution: { status: "idle", tenants: [], error: "" },
    adminPanel: "organization",
    adminBaseCatalog: null,
    adminDocumentLogo: null,
    auth: {
      status: authConfigured ? "loading" : "disabled",
      user: null,
      email: "",
      error: "",
      notice: ""
    }
  };
}
